baseURL: https://coachnamphuong.com
disablePathToLower: true
languageCode: vi-VN
title: Coach Nam Phương

menu:
  main:
    - Name: Giới thiệu
      Weight: 1
      URL: "/about/"
    - Name: Dịch vụ
      Weight: 2
      URL: "/offers/"
    - Name: Bài viết
      Weight: 3
      URL: "/posts/"
    - Name: Chầm chậm
      Weight: 4
      URL: "/cham-cham/"
    - Name: Liên hệ
      Weight: 5
      URL: "mailto:namphuong.cf@gmail.com"

params:
  author: Nam Phương
  default_keywords:
    - health
  default_description: Tôi là Nam Phương - Health Coach, Trainer, Nhà hoạt động xã hội.
    Một 9x lạc quan với quyết tâm giúp bạn trở nên khoẻ mạnh và hạnh phúc.

related:
  threshold: 65
  toLower: true
  includeNewer: true
  indices:
    - name: categories
      weight: 50
    - name: tags
      weight: 100
