baseURL: https://coachnamphuong.com
disablePathToLower: true
languageCode: vi-VN
title: Coach Nam Phương

menu:
  main:
    - Name: About
      Weight: 1
      URL: "/about/"
    - Name: Offers
      Weight: 2
      URL: "/offers/"
    - Name: Blog
      Weight: 3
      URL: "/blog/"
    - Name: Contact
      Weight: 4
      URL: "mailto:namphuong.cf@gmail.com"

params:
  author: Nam Phương
  defaultKeywords:
    - health
  defaultDescription: Coach Nam Phương
