baseURL: /
disablePathToLower: true
languageCode: vi-VN
title: Coach Nam Phương

menu:
  main:
    - Name: About
      Weight: 1
      URL: "/about/"
    - Name: Offers
      Weight: 2
      URL: "/offers/"
    - Name: Blog
      Weight: 3
      URL: "/blog/"
    - Name: Contact
      Weight: 4
      URL: "mailto:namphuong.cf@gmail.com"

params:
  author: Nam Phương
  defaultKeywords:
    - health
  defaultDescription: Coach Nam Phương

  ################################
  # UI Default Text
  ################################
  text:
    # Post Settings
    updated           : Updated
    words_per_minute  : 200
    less_than         : Less than
    minute_read       : min read
    undefined_wpm     : Undefined parameter text.words_per_minute in your theme.yml
    caption           : Image

    # Home Layout Settings
    post_limit        : 5
    read_more         : Read more
    latest_articles   : Recent Posts
    full_archive      : All Posts
    full_archive_url  : /archive/
