baseURL: https://coachnamphuong.com
disablePathToLower: true
languageCode: vi-VN
title: Coach Nam Phương

menu:
  main:
    - Name: About
      Weight: 1
      URL: "/about/"
    - Name: Offers
      Weight: 2
      URL: "/offers/"
    - Name: Blog
      Weight: 3
      URL: "/posts/"
    - Name: Contact
      Weight: 4
      URL: "mailto:namphuong.cf@gmail.com"

params:
  author: Nam Phương
  default_keywords:
    - health
  default_description: Tôi là Nam Phương - Health Coach, Trainer, Nhà hoạt động xã hội.
    Một 9x lạc quan với quyết tâm giúp bạn trở nên khoẻ mạnh và hạnh phúc.
