backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)


media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "post" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "author",     name: "author",     widget: "select", options: ["boo"], default: "boo"}
      - {label: "title",      name: "title",      widget: "string"}
      - {label: "subtitle",   name: "subtitle",   widget: "string", required: false}
      - {label: "pubdate",    name: "date",       widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "draft",      name: "draft",      widget: "boolean", default: true}
      - {label: "body",       name: "body",       widget: "markdown"}
      - {label: "categories", name: "categories", widget: list}
      - {label: "tags",       name: "tags",       widget: list}
      - {label: "description",name: "description",widget: "string", required: false}
      - {label: "cover_image",name: "cover_image",widget: "image",  required: false}

      # - label: "header"
      #   name: "label"
      #   widget: "object"
      #   fields:
      #     - {label: "layout", name: "layout", widget: "string", required: false}
      #     - {label: "image",  name: "image",  widget: "string", required: false}
      #     - {label: "class",  name: "class",  widget: "string", required: false}
      #     - {label: "caption",name: "caption",widget: "string", required: false}
      #     - label: "cta"
      #       name: "cta"
      #       widget: "object"
      #       fields:
      #         - {label: "text",  name: "text",  widget: "string", required: false}
      #         - {label: "url",   name: "url",   widget: "string", required: false}
      #         - {label: "class", name: "class", widget: "string", required: false}
